apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift-bridge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: swift-bridge-service
  template:
    metadata:
      labels:
        component: swift-bridge-service
    spec:
      containers:
        - name: swift-bridge
          image: index.docker.io/octopussolutionsengineering/ghu-swift-bridge:25.12.19152220
          ports:
            - name: http-route
              containerPort: 80
          env:
            - name: DATABASE_SERVER
              value: "development-db"
            - name: DATABASE_NAME
              value: "swift-bridge"
