apiVersion: v1
kind: Service
metadata:
  name: instant-payment-gateway-service
spec:
  type: ClusterIP
  selector:
    component: instant-payment-gateway-service
  ports:
    - port: 80
      targetPort: 80
