apiVersion: apps/v1
kind: Deployment
metadata:
  name: ach-router-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ach-router-service
  template:
    metadata:
      labels:
        component: ach-router-service
    spec:
      containers:
        - name: ach-router
          image: index.docker.io/octopussolutionsengineering/ghu-ach-router:26.01.15222051
          ports:
            - name: http-route
              containerPort: 80
          env:
            - name: DATABASE_SERVER
              value: "production-us-west-1-db"
            - name: DATABASE_NAME
              value: "ach-router"
