apiVersion: apps/v1
kind: Deployment
metadata:
  name: instant-payment-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: instant-payment-gateway-service
  template:
    metadata:
      labels:
        component: instant-payment-gateway-service
    spec:
      containers:
        - name: instant-payment-gateway
          image: index.docker.io/octopussolutionsengineering/ghu-instant-pay-gateway:25.12.18182000
          ports:
            - name: http-route
              containerPort: 80
          env:
            - name: DATABASE_SERVER
              value: "development-us-west-1-db"
            - name: DATABASE_NAME
              value: "ach-router"
